version: '3'

tasks:
  flake-check:
    desc: check whether the flake evaluates and run its tests
    cmds:
      - nix flake check

  flake-update-all:
    desc: update all flake inputs
    cmds:
      - printf "\n> Updating all flake inputs\n\n"
      - nix flake update
    silent: true

  flake-update-one:
    desc: update one flake imput like nixpkgs or flake-utils
    cmds:
      - printf "\n> Updating flake input {{.CLI_ARGS}}\n\n"
      - nix flake lock --update-input {{.CLI_ARGS}}
    silent: true

  pre-commit:
    desc: inizialize pre-commit
    cmds:
      - pre-commit install
    sources:
      - .git/hooks/pre-commit
      - .pre-commit-config.yaml
    generates:
      - .git/hooks/pre-commit
    method: checksum

  pytest:
    desc: run pytest
    cmds:
      - pytest -v -s

  coverage:
    desc: create coverage report
    cmds:
      - pytest --cov=lotb --cov-report=term-missing

  mypy:
    desc: run mypy
    cmds:
      - mypy lotb

  fmt:
    desc: run ruff
    cmds:
      - ruff check --fix
      - ruff format

  local:
    desc: run the app locally
    cmds:
      - nix build .#lotb
      - ./result/bin/lotb --config config.yaml

  test:
    desc: run all tests
    cmds:
      - task: mypy
      - task: pytest
      - task: coverage

  docker-version:
    desc: temp ovverride ver in pyproject.toml if OVERRIDE_VERSION
    silent: true
    cmds:
      - |
        if [ -n "$OVERRIDE_VERSION" ]; then
          sed -i '3s/^version = "[^"]*"/version = "'"$OVERRIDE_VERSION"'"/' pyproject.toml;
        fi

  docker-build:
    desc: build docker img from nix
    deps:
      - docker-version
    cmds:
      - nix build .#dockerimg
      - docker load < result

  docker-push:
    desc: docker push
    silent: true
    cmds:
      - |
        export IMAGE=$(docker images | grep -E "lotb" | awk '{print $1":"$2}' | head -n 1)
        docker push $IMAGE

  docker-compose-recreate:
    desc: restart container
    cmds:
      - docker compose down
      - docker compose up -d

  docker-revamp:
    desc: rebuild and restart container
    cmds:
      - task: docker-build
      - task: docker-compose-recreate
